services:

  mu_bulk_rb:
    container_name: ${mu_bulk_rb_HOSTNAME:-mu_bulk_rb}

    image: redis:7-alpine

  # TODO: Use RabbitMQ as broker
  # mu_bulk_bkr:
  #   image: rabbitmq:4-management-alpine

  # Microservice
  mu_bulk_ms:
    # Hostname for which the service will be reachable
    container_name: ${mu_bulk_ms_HOSTNAME:-mu_bulk_ms}
    build: .
    ports:
      - ${mu_bulk_ms_EXTERNAL_PORT:-8080}:${mu_bulk_ms_INTERNAL_PORT:-8080}
    environment:
      CELERY_BROKER_URL: ${mu_bulk_CELERY_BROKER_URL:-redis://${mu_bulk_rb_HOSTNAME:-mu_bulk_rb}:${mu_bulk_rb_INTERNAL_PORT:-6379}/0}
      CELERY_RESULT_BACKEND: ${mu_bulk_CELERY_RESULT_BACKEND:-redis://${mu_bulk_rb_HOSTNAME:-mu_bulk_rb}:${mu_bulk_rb_INTERNAL_PORT:-6379}/0}
      PORT: ${mu_bulk_ms_INTERNAL_PORT:-8080}
    depends_on:
      - mu_bulk_rb

  # Worker:
  mu_bulk_wkr:
    build: .
    command: celery -A worker.celery worker --loglevel=info
    environment:
      CELERY_BROKER_URL: ${mu_bulk_CELERY_BROKER_URL:-redis://${mu_bulk_rb_HOSTNAME:-mu_bulk_rb}:${mu_bulk_rb_INTERNAL_PORT:-6379}/0}
      CELERY_RESULT_BACKEND: ${mu_bulk_CELERY_RESULT_BACKEND:-redis://${mu_bulk_rb_HOSTNAME:-mu_bulk_rb}:${mu_bulk_rb_INTERNAL_PORT:-6379}/0}
    depends_on:
      - mu_bulk_ms

  # Task dashboard:
  mu_bulk_dashboard:
    container_name: ${mu_bulk_dashboard_HOSTNAME:-mu_bulk_dashboard}
    build: .
    # FIXME: Generalize port by using an environment variable
    command: celery --broker=${mu_bulk_CELERY_BROKER_URL:-redis://${mu_bulk_rb_HOSTNAME:-mu_bulk_rb}:${mu_bulk_rb_INTERNAL_PORT:-6379}/0} flower --port=${mu_bulk_dashboard_INTERNAL_PORT:-5555}
    ports:
      - ${mu_bulk_dashboard_EXTERNAL_PORT:-5555}:${mu_bulk_dashboard_INTERNAL_PORT:-5555}
    environment:
      mu_bulk_CELERY_BROKER_URL: ${mu_bulk_CELERY_BROKER_URL:-redis://${mu_bulk_rb_HOSTNAME:-mu_bulk_rb}:${mu_bulk_rb_INTERNAL_PORT:-6379}/0}
      mu_bulk_dashboard_INTERNAL_PORT: ${mu_bulk_dashboard_INTERNAL_PORT:-5555}
    depends_on:
      - mu_bulk_wkr
